import Head from 'next/head'
import Layout from '../components/layout'


export default function Landing() {
  const leaguesPerCategory = [
    {
      category: "football",
      leagues: ["soccer town", "santa fe FC"]
    },
    {
      category: "basketball",
      leagues: ["olimpico"]
    },
    {
      category: "super smash brothers",
      leagues: ["battlezone"]
    },
  ]

  const leagueRows = leaguesPerCategory.map((category, leagues) =>
  <div className="grid grid-cols-n gap-4 overflow-x-auto">
    <img
    className="rounded-lg"
    src="https://images.unsplash.com/photo-1682407186023-12c70a4a35e0?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2832&q=80"
    alt={category}
    />
  </div>
  );
  return (
    <Layout>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        {leagueRows}
      </Head>
    </Layout>
  )
}
