import Head from 'next/head'
import Layout from '../components/layout'
import * as serviceWorkerRegistration from '../serviceWorkerRegistration';
import reportWebVitals from '../reportWebVitals';

export default function Landing() {
  const leagues = [
    {
      category: "football",
      names: ["soccer town", "santa fe FC"]
    },
    {
      category: "basketball",
      names: ["olimpico"]
    },
    {
      category: "super smash brothers",
      names: ["battlezone"]
    },
  ]

  const leagueRows = leagues.forEach((league) =>
    <div className="grid grid-cols-n gap-4 overflow-x-auto">
      {league.category}
    </div>
  );

  return (
    <Layout>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        {leagueRows}
      </Head>
    </Layout>
  )
}

// serviceWorkerRegistration.register();

reportWebVitals();
