import Head from 'next/head'
import Layout from '../components/layout'
import reportWebVitals from '../reportWebVitals';

export default function Landing() {

  return (
    <Layout>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

    </Layout>
  )
}

// serviceWorkerRegistration.register();

reportWebVitals();
